### ISSUE TITLE
Delayed load time of collections via public URLs

### ISSUE THREAD

**Issue by arblackwell1** [wgu-opensource/osmt#154]
### Describe the bug
When a user clicks the public URL for a collection and the collection landing page loads, it initially looks like there are 0 RSDs in the collection.  Within ~10-20 seconds, however, the page reloads and shows the actual full collection.   

### To Reproduce
1. Go to 'https://osmt.wgu.edu/api/collections/950a0ba5-a70f-431d-a13a-ecefbb5d6bb7'
2. See error

### Expected behavior
When a user clicks the public URL for a collection, they should see the accurate number of RSDs in the collection during the loading of the page.

### Screenshots
<img width="958" alt="Screen Shot 2022-02-07 at 1 45 17 PM" src="https://user-images.githubusercontent.com/69263033/152877272-a2f06d9c-4432-4aaf-bf5c-0cee2bf9ab5f.png">

#### Desktop (please complete the following information):
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 97.0.4692.99

### Additional context
Though the collection does this, this behavior creates a disjointed user experience.

**Comment by JohnKallies** [comment]
@arblackwell1, 

Resolving this would need to start with the team who manages osmt.wgu.edu. The lag you perceive may be a software/source code issue, but there are a lot of things to assess on the servers first (enough CPU, enough RAM, search indexes are updated, etc). Some triage is required before we can identify what changes might be needed.

Unencumbered by actual insights, I'm OK making some wild guesses... We might have issues with serializing a large JSON doc in memory rather than streaming it. Paging or streaming results back to the client might help.

I recommend we close this, at least for now, and get some better insights for what the root issue is.
