### ISSUE TITLE
Support one to many relationships between skills and categories

### ISSUE THREAD

**Issue by DMSaunders** [wgu-opensource/osmt#198]
### Describe the feature request or enhancement you'd like
This is a request from the collabs to enable tagging a skill with multiple categories. 

While it has been noted that the category field has a wide variation in interpretation for how people are using it, this is not a blocker. It is not currently part of our implementation recommendation to explicitly define the use of this field. It is based on CTDL CompetencyCategory which is defined as "The textual label identifying the category of the competency as designated by the promulgating body." Real use is showing demand to have more than one of these categories linked to a single skill.

### Is your feature request related to a problem? 
Enable better mapping of RSDs to existing organizational taxonomies for skills.

The same mechanism that allows multiselect for other properties could potentially be used on this property as well.

**Comment by debeverhart** [comment]
For more information on using the openly licensed, freely available Credential Transparency Description Language (CTDL) for properties for RSDs, so that they will be interoperable with 55K+ skills and 100K+ other entities already in CTDL, see the resources below. 

CTDL concept schemes for controlled vocabularies: https://credreg.net/ctdl/handbook#controlledvocabularies
CTDL competency metadata: https://credreg.net/ctdlasn/terms/Competency#Competency
CTDL handbook: https://credreg.net/ctdl/handbook#ctdlasnschema
CTDL skills in the Registry: https://credentialfinder.org/search?searchType=competencyframework

Note that CTDL provides linked open data structure for many entities that are related to skills, including credentials, courses, jobs, and pathways.

For support using CTDL, contact info@credentialengine.org
